-- adi_db: the ONE database of the five that can be built from the repository.
--
-- The other four (newintegracion, dbadireporte, Presencialformacion,
-- resultadoscalificaciones) hold real integration data and exist only as backups — see
-- 20_newintegracion_synthetic.sql for what the lab does instead, and why the modules that
-- depend on them are reported as NOT COVERED rather than as "no findings".
--
-- Migrations are INCLUDED from the checkout, not copied here. A copy in the profile would go
-- stale the first time the team adds a migration, and the audit would then be measuring a
-- schema nobody deploys.

\connect adi_db

-- DEPLOY.md section 9 creates these by hand before running any migration; 001 assumes they
-- exist. Double-quoted: PostgreSQL folds unquoted identifiers to lower case and the
-- application addresses them in capitals.
CREATE SCHEMA IF NOT EXISTS "ADI";
CREATE SCHEMA IF NOT EXISTS "INTEGRACION";

\echo '--- migraciones del repositorio (001-008) ---'
\i /migrations/001_initial_migration.sql
\i /migrations/002_seed_default_data.sql
\i /migrations/003_performance_indexes.sql
\i /migrations/004_log_histories_indexes.sql
\i /migrations/005_batch_schedule.sql
\i /migrations/006_josso_event.sql
\i /migrations/007_ficha_semilla.sql
-- 008 is committed on `dev` despite DEPLOY.md section 2 warning that it is not — the warning
-- was true of the author's own checkout and went stale. Verified present at 937ec5f. Without
-- it AuthService::authenticate() fails with "column username does not exist", surfacing as a
-- generic 500 that looks like a database outage.
\i /migrations/008_users_username.sql

-- Two tables no backup carries. The application creates them on demand, but only if the
-- PostgreSQL user holds CREATE on schema "ADI"; when it does not, the module fails with
-- "no se pudieron cargar" and no further clue. Creating them here removes that variable from
-- the audit entirely — a failure we then observe is the application's, not the fixture's.
CREATE TABLE IF NOT EXISTS "ADI".manual_integration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inicio TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    fin TIMESTAMP WITHOUT TIME ZONE,
    estado VARCHAR(30) NOT NULL,
    observacion TEXT,
    created_by VARCHAR(30),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "ADI".login_attempts (
    ip varchar(64) PRIMARY KEY,
    attempts integer NOT NULL DEFAULT 0,
    locked_until timestamptz NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);
