-- Tablas que el CÓDIGO usa y que NINGUNA migración commiteada crea.
--
-- ESTO ES UN HALLAZGO, no una utilidad del laboratorio. Se crean aquí para que las rutas que
-- dependen de ellas sean medibles —sin esto /adi/events responde 500 y queda fuera de la matriz
-- de autorización— pero su ausencia en el repositorio es el defecto, y va al informe.
--
-- EVIDENCIA, medida en los dos entornos el 19/08/2026:
--   · app/Models/Event.php:  parent::__construct('ADI', 'synchronized_events')
--   · `grep -rl synchronized_events database/` -> ninguna migración la crea
--   · La base construida SOLO con las migraciones 001-008 tiene `events_without_sync`,
--     no `synchronized_events` -> /adi/events = 500
--   · El despliegue de validación (zajunavideo.com) responde 200 en /adi/events -> allí la
--     tabla EXISTE, creada fuera del control de versiones
--
-- Es la misma clase de defecto que DEPLOY.md ya documenta para la migración 008: el esquema
-- que corre en el servidor no se puede reconstruir desde el repositorio. Un despliegue nuevo
-- —o una recuperación ante desastre— arranca roto y el error es un 500 genérico que no dice
-- cuál es la tabla, porque EventService.php:56 hace `catch (Exception)` y descarta la causa.
--
-- La estructura de abajo está DEDUCIDA del uso, no copiada de producción: si el equipo aporta
-- la definición real, sustitúyase, y hasta entonces cualquier conclusión sobre el CONTENIDO de
-- esta tabla es NO AUTORITATIVA.

\connect adi_db

CREATE TABLE IF NOT EXISTS "ADI".synchronized_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type   VARCHAR(80),
    description  TEXT,
    status       VARCHAR(30),
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL
);

INSERT INTO "ADI".synchronized_events (event_type, description, status)
VALUES ('SINCRONIZACION', 'evento sintetico de laboratorio', 'OK')
ON CONFLICT DO NOTHING;

-- LOG_TRANSAC — en adi_db, NO en newintegracion.
--
-- app/Models/ApiLog.php declara el ESQUEMA 'INTEGRACION' pero usa la conexión por defecto
-- (App::db() -> DB_DATABASE=adi_db). Puesta primero en newintegracion, /adi/api seguía dando
-- 500 y el log de postgres lo dijo sin ambigüedad: el error salía de adi_db. Un esquema con el
-- mismo nombre en dos bases es una trampa fácil de pisar.
--
-- Original: la lee app/Models/ApiLog.php ('INTEGRACION', 'LOG_TRANSAC'). Sin ella
-- /adi/api responde 500 y la ruta queda fuera de la matriz de autorización — que era el
-- caso hasta que se comprobó en el navegador. Estructura mínima deducida del uso.
CREATE TABLE IF NOT EXISTS "INTEGRACION"."LOG_TRANSAC" (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ID_LOG"      BIGINT,
    "FECHA"       TIMESTAMP,
    "OPERACION"   VARCHAR(80),
    "ESTADO"      VARCHAR(30),
    "DETALLE"     TEXT
);
INSERT INTO "INTEGRACION"."LOG_TRANSAC" ("ID_LOG","FECHA","OPERACION","ESTADO","DETALLE") VALUES
  (1, '2026-08-01 09:00:00', 'ENROLL',  'OK',    'transaccion sintetica'),
  (2, '2026-08-02 10:30:00', 'NOVEDAD', 'ERROR', 'transaccion sintetica con error')
ON CONFLICT DO NOTHING;

-- LÍMITE DECLARADO, y aquí se para de deducir.
--
-- `/adi/events` sigue devolviendo 500 con esta estructura: el modelo espera más columnas de las
-- que se pueden inferir del código sin ver el esquema real. Seguir añadiendo columnas hasta que
-- la pantalla cargue sería fabricar el objeto que decimos estar midiendo, y cualquier resultado
-- posterior hablaría de la invención del laboratorio y no de la aplicación.
--
-- Estado, y así va al informe:
--   · pelmaño 3 local  -> /adi/events NO CUBIERTO. Razón: el esquema no es reconstruible desde
--                         el repositorio. La razón ES el hallazgo.
--   · despliegue vivo  -> /adi/events responde 200 (medido 19/08/2026): allí la tabla existe,
--                         creada fuera del control de versiones.
-- Se cierra el día que el equipo entregue la definición real o commitee la migración.
