-- The two accounts of DIFFERENT privilege the authorization matrix needs.
--
-- Not optional and not a convenience: authorization is the one dimension no scanner can test
-- on its own, and testing it needs a low-privilege account that ATTEMPTS what only the
-- high-privilege one may do. With one account, or two of equal rank, the whole dimension is
-- unmeasurable and `make gate` reports it as blocked rather than passed.
--
-- Roles come from app/Enums/UserRolesEnum.php: 'super' (SuperAdmin) and 'support' (Support).
-- Any account restored from a backup has a hash whose password nobody knows, so these are
-- created here with hashes generated by PHP's own password_hash(PASSWORD_DEFAULT).
--
-- SYNTHETIC, and deliberately so: the lab's data policy prefers invented accounts to real
-- ones, and a profile whose credentials are real must set CREDS_ARE_REAL=yes and stay out of
-- version control. These are safe to publish — they only exist inside an ephemeral container
-- bound to 127.0.0.1 that `make down` destroys.

\connect adi_db

INSERT INTO "ADI".users (num_id, tipe_id, name, email, username, password, role)
VALUES (900000001, 'cc', 'Lab Super', 'lab_super@lab.test', 'lab_super',
        '$2y$10$nAWzAsRK3S/V7K.W66.mgOGmZIOOW4Mr7u0hP3FOH/9j.GiM/pZcS', 'super')
ON CONFLICT (num_id) DO UPDATE
   SET password = EXCLUDED.password, role = EXCLUDED.role, username = EXCLUDED.username;

INSERT INTO "ADI".users (num_id, tipe_id, name, email, username, password, role)
VALUES (900000002, 'cc', 'Lab Support', 'lab_support@lab.test', 'lab_support',
        '$2y$10$Q3yorVI5uDsCckK8.bKEVuuhsnv6eL8ZkG.KNMGPX6sac2HDz5/Hy', 'support')
ON CONFLICT (num_id) DO UPDATE
   SET password = EXCLUDED.password, role = EXCLUDED.role, username = EXCLUDED.username;

-- Start every run with a clean rate limiter. ADI locks an IP after 5 failed attempts for 15
-- minutes; a leftover row from a previous run would make the suite's first login fail and
-- every authorization test would then report a failure that belongs to the lab, not the app.
DELETE FROM "ADI".login_attempts;
